Repository SteamRE/SteamKit, pull requests merged in 2021-11, with the labels that each got.

#1047 Catch BeginConnect exceptions in TcpConnection
  SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs
Labels: bug

#1050 Fix unobserved task exception under .NET 6 runtime
  SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs
Labels: bug

#1022 Refactor CDN client
  SteamKit2/SteamKit2/Steam/CDN/Client.cs
  SteamKit2/SteamKit2/Steam/CDN/DepotChunk.cs
  SteamKit2/SteamKit2/Steam/CDN/Server.cs
  SteamKit2/SteamKit2/Steam/CDNClient.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamContent/SteamContent.cs
  SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs
  SteamKit2/SteamKit2/Steam/WebAPI/ContentServerDirectoryService.cs
  SteamKit2/Tests/CDNClientFacts.cs
Labels: breaking change

#1036 Use non-legacy service methods (and some refactoring of messages/packets handling)
  SteamKit2/SteamKit2/Base/ClientMsg.cs
  SteamKit2/SteamKit2/Base/MsgBase.cs
  SteamKit2/SteamKit2/Base/PacketBase.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUnifiedMessages/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUnifiedMessages/SteamUnifiedMessages.cs
Labels: hacktoberfest-accepted
