Repository SteamRE/SteamKit, pull requests merged in 2024-08, with the labels that each got.

#1393 Add steam deck support to logon
  SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs
Labels: enhancement

#1397 Use `BufferBlock` for the callbacks queue
  SteamKit2/SteamKit2/Steam/SteamClient/CallbackMgr/CallbackMgr.cs
  SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs
  SteamKit2/SteamKit2/changes.txt
  SteamKit2/Tests/CallbackManagerFacts.cs
  SteamKit2/Tests/SteamGameServerFacts.cs
  SteamKit2/Tests/SteamUserFacts.cs
Labels: enhancement

#1389 Reuse `StringBuilder` in `KVTextReader`
  SteamKit2/SteamKit2/Types/KeyValue.cs
Labels: enhancement

#1379 Less allocations in non-utf8 string reads, fix non-utf8 string writes, optimize both with stack / pool alloc
  SteamKit2/SteamKit2/Base/MsgBase.cs
  SteamKit2/SteamKit2/Util/StreamHelpers.cs
  SteamKit2/Tests/StreamHelpersFacts.cs
Labels: enhancement

#1386 Store depot chunk crc as uint to avoid converting to bytes
  SteamKit2/SteamKit2/Steam/CDN/DepotChunk.cs
  SteamKit2/SteamKit2/Types/DepotManifest.cs
  SteamKit2/SteamKit2/Types/Manifest.cs
  SteamKit2/SteamKit2/Util/Utils.cs
Labels: enhancement, breaking change

#1392 Delete `SteamTrading` handler
  SteamKit2/SteamKit2/Steam/Handlers/SteamTrading/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamTrading/SteamTrading.cs
  SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs
  SteamKit2/Tests/SteamClientFacts.cs
Labels: breaking change

#1395 Make exceptions serializable, have standard constructors
  .editorconfig
  SteamKit2/SteamKit2/Steam/Authentication/AuthenticationException.cs
  SteamKit2/SteamKit2/Steam/SteamClient/AsyncJobFailedException.cs
  SteamKit2/SteamKit2/Steam/SteamClient/AsyncJobManager.cs
  SteamKit2/SteamKit2/Steam/WebAPI/WebAPIRequestException.cs
  SteamKit2/SteamKit2/Util/SteamKitWebRequestException.cs
Labels: enhancement

#1398 Add test coverage
  .github/codecov.yml
  .github/workflows/steamkit2-build.yaml
  .gitignore
  SteamKit2/Tests/Tests.csproj
Labels: enhancement

#1391 Make client msg handlers a simple list
  SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs
  SteamKit2/Tests/SteamClientFacts.cs
Labels: enhancement

#1390 Simplify callback dispatching
  SteamKit2/SteamKit2/Steam/Handlers/SteamApps/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamApps/SteamApps.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamCloud/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamCloud/SteamCloud.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamFriends/SteamFriends.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamGameCoordinator/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamGameCoordinator/SteamGameCoordinator.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamGameServer/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamGameServer/SteamGameServer.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamMasterServer/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamMasterServer/SteamMasterServer.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamMatchmaking/SteamMatchmaking.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamNetworking/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamNetworking/SteamNetworking.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamScreenshots/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamScreenshots/SteamScreenshots.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUnifiedMessages/SteamUnifiedMessages.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUser/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUser/SteamUser.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUserStats/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamUserStats/SteamUserStats.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamWorkshop/Callbacks.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamWorkshop/SteamWorkshop.cs
  SteamKit2/SteamKit2/Steam/SteamClient/SteamClient.cs
Labels: enhancement

#1388 Remove compressed buffer allocation in VZipUtil
  SteamKit2/SteamKit2/Util/VZipUtil.cs
Labels: enhancement

#1387 Use ZipArchive in ZipUtil
  SteamKit2/SteamKit2/Util/ZipUtil.cs
Labels: enhancement

#1385 Optimize `DecryptFilenames`
  SteamKit2/SteamKit2/Types/DepotManifest.cs
  SteamKit2/Tests/DepotManifestFacts.cs
  SteamKit2/Tests/Files/depot_440_1118032470228587934.zip
  SteamKit2/Tests/Tests.csproj
Labels: enhancement

#1384 Reduce allocations
  SteamKit2/SteamKit2/Base/Generated/SteamLanguageInternal.cs
  SteamKit2/SteamKit2/Steam/CMClient.cs
  SteamKit2/SteamKit2/Steam/Handlers/SteamApps/Callbacks.cs
  SteamKit2/SteamKit2/Types/DepotManifest.cs
  SteamKit2/SteamKit2/Util/HardwareUtils.cs
Labels: enhancement

#1382 Optimize gzip in HandleMulti
  SteamKit2/SteamKit2/Steam/CMClient.cs
  SteamKit2/SteamKit2/Util/StreamHelpers.cs
Labels: enhancement

#1381 Improve encryption allocations
  SteamKit2/SteamKit2/Networking/Steam3/EnvelopeEncryptedConnection.cs
  SteamKit2/SteamKit2/Networking/Steam3/IConnection.cs
  SteamKit2/SteamKit2/Networking/Steam3/INetFilterEncryption.cs
  SteamKit2/SteamKit2/Networking/Steam3/NetFilterEncryption.cs
  SteamKit2/SteamKit2/Networking/Steam3/NetFilterEncryptionWithHMAC.cs
  SteamKit2/SteamKit2/Networking/Steam3/TcpConnection.cs
  SteamKit2/SteamKit2/Networking/Steam3/UdpConnection.cs
  SteamKit2/SteamKit2/Networking/Steam3/WebSocketConnection.cs
  SteamKit2/SteamKit2/Networking/Steam3/WebSocketContext.cs
  SteamKit2/SteamKit2/Util/CryptoHelper.cs
  SteamKit2/Tests/CryptoHelperFacts.cs
Labels: enhancement

#1383 Use ArrayPool for reading websocket messages
  SteamKit2/SteamKit2/Networking/Steam3/WebSocketContext.cs
Labels: enhancement

#1404 Optimize downloading depot chunks and manifests
  SteamKit2/SteamKit2/Steam/CDN/Client.cs
  SteamKit2/SteamKit2/Steam/CDN/DepotChunk.cs
  SteamKit2/SteamKit2/Types/DepotManifest.cs
  SteamKit2/SteamKit2/Types/Manifest.cs
  SteamKit2/SteamKit2/Util/CryptoHelper.cs
  SteamKit2/SteamKit2/Util/LZMA/Compress/LZ/LzOutWindow.cs
  SteamKit2/SteamKit2/Util/LZMA/Compress/LZMA/LzmaDecoder.cs
  SteamKit2/SteamKit2/Util/Utils.cs
  SteamKit2/SteamKit2/Util/VZipUtil.cs
  SteamKit2/SteamKit2/Util/ZipUtil.cs
  SteamKit2/Tests/CDNClientFacts.cs
  SteamKit2/Tests/DepotManifestFacts.cs
  SteamKit2/Tests/Files/depot_440_1118032470228587934.manifest
  SteamKit2/Tests/Files/depot_440_1118032470228587934.zip
Labels: enhancement

#1124 Replace CA2101 suppression with disabling BestFitMapping
  SteamKit2/SteamKit2/Util/MacHelpers.cs
Labels: bug
